# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Galaxea R1 Pro robot configurations (planner / model side).

Single-arm RobotConfig factory for the R1Pro, used for planning (Drake) and
visualization (viser). The full-body URDF (mobile base + torso + both arms)
loads with the base welded to the world; only the chosen arm's 7 revolute
joints are driven, the rest stay welded at their zero pose.

Asset: ``data/r1pro_urdf/`` (package ``r1pro_urdf``), meshes referenced as
``package://r1pro_urdf/meshes/*.STL``.
"""

from __future__ import annotations

from typing import Any

from dimos.robot.config import GripperConfig, RobotConfig
from dimos.utils.data import LfsPath

R1PRO_PKG = LfsPath("r1pro_urdf")
# Full-body URDF (mobile base + torso + both arms): 46 links / 28 joints.
R1PRO_FULL_MODEL_PATH = R1PRO_PKG / "urdf" / "r1pro.urdf"
# MuJoCo sim asset (dual-arm: 18 actuated joints + 2 grippers + head scan_camera),
# generated from the full URDF by data/r1pro_urdf/tools/make_r1pro_mjcf.py.
R1PRO_SIM_MJCF_PATH = R1PRO_PKG / "mujoco" / "r1pro_dual.xml"
R1PRO_SIM_MESHDIR = R1PRO_PKG / "mujoco" / "assets"
# Arm-only URDF (left arm + gripper + wrist camera, rooted at left_arm_base_link):
# 12 links / 7 revolute joints. ~4x fewer link transforms to render/update per frame,
# which is what the viser gizmo preview and 10Hz render push to the browser.
# Generated by .local/make_r1pro_arm.py. This is the default model.
R1PRO_MODEL_PATH = R1PRO_PKG / "urdf" / "r1pro_left_arm.urdf"
# World placement of left_arm_base_link on the full robot at zero config (so the
# arm-only model welds where the shoulder actually sits). Computed by the generator.
R1PRO_ARM_BASE_POSE: list[float] = [-0.079518, 0.097234, 1.451290, 0.0, 0.0, 0.0, 1.0]

# Bent-elbow "ready" home pose (radians, 7 arm joints). The all-zero pose is a
# cramped config (joint2 near its lower limit, joint4 near its upper) that makes
# a terrible IK seed — planning thrashes or fails. This raised, bent-elbow pose
# sits well inside joint limits and is a good seed for differential/Jacobian IK.
R1PRO_READY_HOME: list[float] = [0.0, 1.0, 0.0, -1.0, 0.0, 0.6, 0.0]

# Collision exclusion pairs — structural mesh overlaps in the full-body URDF
# plus gripper parallel-linkage exclusions. Link names verified against
# data/r1pro_urdf/urdf/r1pro.urdf (wrist camera is *_realsense_link).
R1PRO_COLLISION_EXCLUSIONS: list[tuple[str, str]] = [
    # Chassis <-> wheels/steers (mesh overlap at zero pose)
    ("base_link", "wheel_motor_link1"),
    ("base_link", "wheel_motor_link2"),
    ("base_link", "wheel_motor_link3"),
    ("base_link", "steer_motor_link1"),
    ("base_link", "steer_motor_link2"),
    ("base_link", "steer_motor_link3"),
    # Torso <-> arm shoulders (tight mesh fit)
    ("torso_link4", "left_arm_link1"),
    ("torso_link4", "right_arm_link1"),
    ("torso_link4", "left_arm_base_link"),
    ("torso_link4", "right_arm_base_link"),
    # Non-adjacent arm links that overlap at zero pose (link5 <-> link7)
    ("left_arm_link5", "left_arm_link7"),
    ("right_arm_link5", "right_arm_link7"),
    # Left gripper + wrist camera
    ("left_arm_link7", "left_gripper_link"),
    ("left_gripper_link", "left_gripper_finger_link1"),
    ("left_gripper_link", "left_gripper_finger_link2"),
    ("left_gripper_finger_link1", "left_gripper_finger_link2"),
    ("left_gripper_link", "left_realsense_link"),
    ("left_arm_link7", "left_realsense_link"),
    # Right gripper + wrist camera
    ("right_arm_link7", "right_gripper_link"),
    ("right_gripper_link", "right_gripper_finger_link1"),
    ("right_gripper_link", "right_gripper_finger_link2"),
    ("right_gripper_finger_link1", "right_gripper_finger_link2"),
    ("right_gripper_link", "right_realsense_link"),
    ("right_arm_link7", "right_realsense_link"),
]

# Subset valid for the arm-only URDF (the torso/chassis pairs are gone with the body).
R1PRO_ARM_EXCLUSIONS: list[tuple[str, str]] = [
    ("left_arm_link5", "left_arm_link7"),
    ("left_arm_link7", "left_gripper_link"),
    ("left_gripper_link", "left_gripper_finger_link1"),
    ("left_gripper_link", "left_gripper_finger_link2"),
    ("left_gripper_finger_link1", "left_gripper_finger_link2"),
    ("left_gripper_link", "left_realsense_link"),
    ("left_arm_link7", "left_realsense_link"),
]


def r1pro_arm(
    side: str = "left",
    name: str | None = None,
    *,
    adapter_type: str = "mock",
    address: str | None = None,
    add_gripper: bool = False,
    **overrides: Any,
) -> RobotConfig:
    """R1 Pro single-arm RobotConfig (planner / Drake / viser model).

    Uses the ARM-ONLY URDF by default (rooted at ``{side}_arm_base_link``, welded
    at the shoulder's real world placement). Only ``side='left'`` ships an arm-only
    URDF today; pass ``model_path=R1PRO_FULL_MODEL_PATH`` + ``base_link='base_link'``
    to use the full body instead.

    Note: the R1Pro gripper has two independent prismatic fingers
    (``{side}_gripper_finger_joint1`` opens 0->0.05, ``joint2`` mirrors
    -0.05->0). Only ``joint1`` is driven by the scalar gripper command; the
    second finger is handled as a visual mirror (TODO: wire mimic in sim/viz).
    """
    if side not in ("left", "right"):
        raise ValueError(f"side must be 'left' or 'right', got {side!r}")

    resolved_name = name or f"r1pro_{side}_arm"
    joint_names = [f"{side}_arm_joint{i}" for i in range(1, 8)]
    ee_link = f"{side}_arm_link7"

    gripper = None
    if add_gripper:
        gripper = GripperConfig(
            type="r1pro",
            joints=[f"{side}_gripper_finger_joint1"],
            collision_exclusions=list(R1PRO_ARM_EXCLUSIONS),
            open_position=0.04,
            close_position=0.0,
        )

    defaults: dict[str, Any] = {
        "name": resolved_name,
        "model_path": R1PRO_MODEL_PATH,
        "end_effector_link": ee_link,
        "adapter_type": adapter_type,
        "address": address,
        "joint_names": joint_names,
        "base_link": f"{side}_arm_base_link",
        "home_joints": list(R1PRO_READY_HOME),
        "base_pose": list(R1PRO_ARM_BASE_POSE),
        "package_paths": {"r1pro_urdf": R1PRO_PKG},
        "auto_convert_meshes": True,
        "collision_exclusion_pairs": list(R1PRO_ARM_EXCLUSIONS),
        "max_velocity": 0.5,
        "max_acceleration": 1.0,
        "gripper": gripper,
        "tf_extra_links": [f"{side}_realsense_link"],
        "adapter_kwargs": {"side": side},
    }
    defaults.update(overrides)
    return RobotConfig(**defaults)


# --- Bimanual (dual-arm) -------------------------------------------------------
# Dual-arm URDF: base_link + torso(frozen) + BOTH arms, 14 actuated joints.
R1PRO_DUAL_MODEL_PATH = R1PRO_PKG / "urdf" / "r1pro_dual_arm.urdf"
# Per-arm end-effector tip (the pose-target frame for each planning group).
R1PRO_ARM_TIPS: dict[str, str] = {"left": "left_arm_link7", "right": "right_arm_link7"}


def _dual_arm_links() -> set[str]:
    links = {"base_link", *(f"torso_link{i}" for i in range(1, 5))}
    for side in ("left", "right"):
        links |= {
            f"{side}_arm_base_link",
            *(f"{side}_arm_link{i}" for i in range(1, 8)),
            f"{side}_gripper_link",
            f"{side}_gripper_finger_link1",
            f"{side}_gripper_finger_link2",
            f"{side}_realsense_link",
        }
    return links


# Full-body exclusions filtered to the links present in the dual-arm model.
R1PRO_DUAL_EXCLUSIONS: list[tuple[str, str]] = [
    pair
    for pair in R1PRO_COLLISION_EXCLUSIONS
    if pair[0] in _dual_arm_links() and pair[1] in _dual_arm_links()
]


def r1pro_bimanual(
    name: str = "r1pro",
    *,
    adapter_type: str = "mock",
    address: str | None = None,
    add_gripper: bool = False,
    **overrides: Any,
) -> RobotConfig:
    """R1 Pro dual-arm RobotConfig for bimanual planning.

    One robot whose controlled joints are BOTH arms (14 DOF, left then right).
    Bimanual planning targets each arm tip in ``R1PRO_ARM_TIPS`` simultaneously
    via multi-target IK; ``end_effector_link`` is a nominal single-arm default.
    ``home_joints`` is the all-zeros configuration: torso upright and both arms
    hanging naturally at the sides (collision-free, well inside the mirrored
    joint limits, so a clean IK seed). RoboPlan's fast collision checking means
    no specially-tuned seed pose is needed.
    """
    # 18 DOF: torso (4) is a free DOF so the robot can lean to extend reach, plus
    # both 7-DOF arms. Order: torso, left, right.
    joint_names = [f"torso_joint{i}" for i in range(1, 5)] + [
        f"{side}_arm_joint{i}" for side in ("left", "right") for i in range(1, 8)
    ]
    defaults: dict[str, Any] = {
        "name": name,
        "model_path": R1PRO_DUAL_MODEL_PATH,
        "end_effector_link": "left_arm_link7",
        "adapter_type": adapter_type,
        "address": address,
        "joint_names": joint_names,
        "base_link": "base_link",
        "home_joints": [0.0] * 18,
        "base_pose": [0, 0, 0, 0, 0, 0, 1],
        "package_paths": {"r1pro_urdf": R1PRO_PKG},
        "auto_convert_meshes": True,
        # Full body is present (head/chassis/torso frozen) so exclude the static
        # chassis self-overlaps too, else the robot reads as always-in-collision.
        "collision_exclusion_pairs": R1PRO_COLLISION_EXCLUSIONS,
        "max_velocity": 0.5,
        "max_acceleration": 1.0,
        # {side}_arm_link7 is the wrist; the gripper fingertips sit ~0.2 m beyond it.
        # Drive grasp targets to the fingertips (approach aligned to the pose +Z), per arm
        # so the pick can grasp with either hand.
        "grasp_tcp_links": {
            "left": (
                "left_arm_link7",
                "left_gripper_finger_link1",
                "left_gripper_finger_link2",
            ),
            "right": (
                "right_arm_link7",
                "right_gripper_finger_link1",
                "right_gripper_finger_link2",
            ),
        },
    }
    if add_gripper:
        # Both grippers, in SIDE ORDER: list position 0 -> left (SHM side 0), 1 -> right
        # (SHM side 1). The MuJoCo sim drives gripper actuators 18 (left) / 19 (right);
        # the control stack routes per-side by this list order. Finger range is
        # [0 closed, 0.05 open].
        defaults["gripper"] = GripperConfig(
            type="r1pro",
            joints=["left_gripper", "right_gripper"],
            open_position=0.05,
            close_position=0.0,
        )
    defaults.update(overrides)
    return RobotConfig(**defaults)


__all__ = [
    "R1PRO_ARM_TIPS",
    "R1PRO_COLLISION_EXCLUSIONS",
    "R1PRO_DUAL_MODEL_PATH",
    "R1PRO_MODEL_PATH",
    "r1pro_arm",
    "r1pro_bimanual",
]
