# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The single file the agent edits. It defines the Point-LIO configuration
(CONFIG), runs the offline LIO on the recorded Go2 stream to produce an
odometry trajectory, scores it against robot_odom ground truth via the frozen
harness in evaluate.py, and prints a summary block.

The Point-LIO C++ substrate (point_lio/) and the evaluation (evaluate.py) are
fixed. You tune CONFIG (and, if you want, the Python pre/post-processing in
this file). The goal: minimize `val_ate_xy` — the 2D trajectory error vs the
robot's leg-inertial odometry ground truth.

Baseline CONFIG below = the "v2_imu" config: IMU-coupled, with the corrections
that matter for this Go2-L1 unit — measured acc_norm 10.434, imu_time_inte
0.004 (~250 Hz IMU), and extrinsic_R = Rx(pi) = diag(1,-1,-1) for the IMU's
180-deg roll vs the lidar. Run this as-is first to establish the baseline.
"""

import os
import subprocess
import time

import evaluate

# ----------------------------------------------------------------------------
# CONFIG — the knobs you tune. These map 1:1 to the Point-LIO yaml.
# ----------------------------------------------------------------------------
CONFIG = {
    # preprocess
    "lidar_type": 5,  # 5 = unilidar L1
    "scan_line": 18,
    "timestamp_unit": 0,  # per-point time is in SECONDS (validated)
    "blind": 0.5,  # ignore returns closer than this (m)
    # mapping / EKF
    "imu_en": True,
    "imu_time_inte": 0.004,  # ~250 Hz IMU integration dt
    "acc_norm": 10.434,  # measured static |g| for this Go2-L1 IMU
    "lidar_meas_cov": 0.01,
    "plane_thr": 0.1,
    "match_s": 81,
    "filter_size_surf": 0.1,  # downsample voxel size (surf), m
    "filter_size_map": 0.1,  # downsample voxel size (map), m
    "fov_degree": 180,
    "det_range": 100.0,
    "gravity_align": True,
    "start_in_aggressive_motion": False,
    "extrinsic_est_en": False,
    # IMU process / measurement covariances
    "satu_acc": 30.0,
    "satu_gyro": 35,
    "acc_cov_output": 500,
    "gyr_cov_output": 1000,
    "b_acc_cov": 0.0001,
    "b_gyr_cov": 0.0001,
    "imu_meas_acc_cov": 0.1,
    "imu_meas_omg_cov": 0.1,
    "gyr_cov_input": 0.01,
    "acc_cov_input": 0.1,
    # extrinsics (imu -> lidar). Rx(pi) handles the L1 IMU's 180-deg roll.
    "extrinsic_T": [0, 0, 0],
    "extrinsic_R": [1, 0, 0, 0, -1, 0, 0, 0, -1],
}


def write_yaml(cfg, path):
    R = cfg["extrinsic_R"]
    T = cfg["extrinsic_T"]
    txt = f"""# auto-generated by algo.py — do not hand-edit; edit CONFIG in algo.py
common:
    lid_topic: "/unilidar/cloud"
    imu_topic: "/unilidar/imu"
    con_frame: false
    con_frame_num: 1
    cut_frame: false
    cut_frame_time_interval: 0.1
    time_lag_imu_to_lidar: 0.0
preprocess:
    lidar_type: {cfg["lidar_type"]}
    scan_line: {cfg["scan_line"]}
    timestamp_unit: {cfg["timestamp_unit"]}
    blind: {cfg["blind"]}
mapping:
    imu_en: {str(cfg["imu_en"]).lower()}
    start_in_aggressive_motion: {str(cfg["start_in_aggressive_motion"]).lower()}
    extrinsic_est_en: {str(cfg["extrinsic_est_en"]).lower()}
    imu_time_inte: {cfg["imu_time_inte"]}
    filter_size_surf: {cfg["filter_size_surf"]}
    filter_size_map: {cfg["filter_size_map"]}
    satu_acc: {cfg["satu_acc"]}
    satu_gyro: {cfg["satu_gyro"]}
    acc_norm: {cfg["acc_norm"]}
    lidar_meas_cov: {cfg["lidar_meas_cov"]}
    acc_cov_output: {cfg["acc_cov_output"]}
    gyr_cov_output: {cfg["gyr_cov_output"]}
    b_acc_cov: {cfg["b_acc_cov"]}
    b_gyr_cov: {cfg["b_gyr_cov"]}
    imu_meas_acc_cov: {cfg["imu_meas_acc_cov"]}
    imu_meas_omg_cov: {cfg["imu_meas_omg_cov"]}
    gyr_cov_input: {cfg["gyr_cov_input"]}
    acc_cov_input: {cfg["acc_cov_input"]}
    plane_thr: {cfg["plane_thr"]}
    match_s: {cfg["match_s"]}
    fov_degree: {cfg["fov_degree"]}
    det_range: {cfg["det_range"]}
    gravity_align: {str(cfg["gravity_align"]).lower()}
    gravity: [0.0, 0.0, -9.810]
    gravity_init: [0.0, 0.0, -9.810]
    extrinsic_T: [ {T[0]}, {T[1]}, {T[2]} ]
    extrinsic_R: [ {R[0]}, {R[1]}, {R[2]}, {R[3]}, {R[4]}, {R[5]}, {R[6]}, {R[7]}, {R[8]} ]
odometry:
    publish_odometry_without_downsample: enable
publish:
    path_en: true
    scan_publish_en: true
    scan_bodyframe_pub_en: false
pcd_save:
    pcd_save_en: false
    interval: -1
"""
    with open(path, "w") as f:
        f.write(txt)


def main():
    if not os.path.exists(evaluate.POINTLIO_BIN):
        raise SystemExit("pointlio binary not built — run ./setup.sh first.")
    write_yaml(CONFIG, evaluate.ACTIVE_YAML)
    if os.path.exists(evaluate.TRAJ_PATH):
        os.remove(evaluate.TRAJ_PATH)

    t0 = time.time()
    try:
        subprocess.run(
            [evaluate.POINTLIO_BIN, "--yaml", evaluate.ACTIVE_YAML, "--bin", evaluate.BIN_PATH],
            cwd=evaluate.POINTLIO_DIR,
            timeout=evaluate.RUN_TIMEOUT,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.TimeoutExpired:
        raise SystemExit(f"run exceeded {evaluate.RUN_TIMEOUT}s — treat as failure")
    run_s = time.time() - t0

    m = evaluate.evaluate()  # raises if trajectory missing/malformed (= crash)

    print("---")
    print(f"val_ate_xy:        {m['val_ate_xy']:.6f}")
    print(f"final_err_xy:      {m['final_err_xy']:.3f}")
    print(f"loop_close_xy:     {m['loop_close_xy']:.3f}")
    print(f"gt_loop_xy:        {m['gt_loop_xy']:.3f}")
    print(f"path_len:          {m['path_len']:.2f}")
    print(f"gt_path_len:       {m['gt_path_len']:.2f}")
    print(f"num_poses:         {m['num_poses']}")
    print(f"overlap_s:         {m['overlap_s']:.1f}")
    print(f"run_seconds:       {run_s:.1f}")

    # Render viz.png + downsampled traj_ds.tsv for this run (non-fatal: a plotting
    # failure must never fail the experiment). Commit these on a "keep".
    try:
        import visualize

        visualize.render()
    except Exception as e:
        print(f"(visualize skipped: {e})")


if __name__ == "__main__":
    main()
